#!/usr/bin/env bash
# Displays the number from 1 to 100 as well as fizz in place of multiples of 3, Buzz in place of multiples of 5 and FizzBuzz in place of multiples of both
counter=0
while [ $counter -lt 100 ]
do
((counter++))
if (($counter % 15 == 0))
then
echo "FizzBuzz"
elif (($counter % 5 == 0)) 
then
echo "Buzz"
elif (($counter % 3 == 0))
then
echo "Fizz"
else
echo $counter
fi
done
