#!/usr/bin/env bash
# This is a script that prints numbers and alternate text in special cases
counter=0
while [ $counter -lt 20 ]
do
((counter++))
echo $counter
case $counter in
4)
echo "bad luck from China"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy"
;;
esac
done
