#!/usr/bin/env bash
# Configures an Ubuntu server with localhost as 127.0.0.2 and facebook.com as 8.8.8.8
cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
